//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolJournal.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableColumns
    {
        public long id { get; set; }
        public byte type { get; set; }
        public System.DateTime date { get; set; }
    }
}
